version: "3"
services:
  auth-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - template.env
    network_mode: "host"
    ports:
      - '3306:3306'
  emba:
    image: emba:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    volumes:
        - ${FIRMWARE}/:/firmware
        - ${LOG}/:/log
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/:/tmp/
        - ./embark/:/app/embark/
    network_mode: "host"
    ports:
      - '8000:8000'
      - '8001:8001'
    env_file:
      - template.env
    command: './entrypoint.sh'
    environment:
        - USER