version: "3"

services:

  embark_db:
    image: mysql
    container_name: embark_db
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_PASSWORD
      - MYSQL_USER
      - MYSQL_DATABASE
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - backend

  embark:
    image: embark:latest
    container_name: embark_server
    build: .
    restart: always
    privileged: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
        - ./embark/:/app/embark/
        - ./emba/:/app/emba/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    networks:
      - embark_frontend
      - embark_backend
    env_file: 
      - .env
    environment:
      - DATABASE_NAME
      - DATABASE_USER
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_PASSWORD
      - DJANGO_LOG_LEVEL
      - DEBUG=False
      - REDIS_HOST
      - REDIS_PORT
    command: './entrypoint.sh'
    depends_on:
        - embark_db
        - redis

  redis:
    image: "redis:5"
    container_name: embark_redis
    command: --port 7777
    expose:
      - "7777"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - embark_backend

networks:
  embark_frontend:
    name: embark_frontend
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: embark_frontend

  embark_backend:
    name: embark_backend
    driver: ipvlan
    internal: true
    ipam:
      config:
        - subnet: "172.22.0.0/16"


